#!/usr/bin/env python3
# Copyright 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Turn tests/protocol_vectors.txt into a generated C header of typed byte
arrays, for tests/unit/protocol_vectors/ (issue #31 finding E5, the
firmware-side wire-vector consumer CONTRIBUTING.md claims but that did not
exist).

Run at BUILD time by tests/unit/CMakeLists.txt's protocol-vectors-header
custom command -- never committed, mirroring cmake/gen_build_id.cmake's
generate-don't-parse precedent: the consumer suite gets no runtime file-IO
dependency (no cwd-relative path to resolve under ctest) and no hand-rolled
hex-to-byte parser sitting in C, where -Wconversion would have opinions about
every implicit narrowing in a routine that never had to exist.

Usage:
    python3 tests/gen_protocol_vectors_header.py <vectors.txt> <out.h>
"""

from __future__ import annotations

import os
import re
import sys

_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_vectors(path: str) -> list[tuple[str, bytes]]:
    """Parse `name = HEXBYTES` lines; '#'-prefixed lines are comments."""
    vectors: list[tuple[str, bytes]] = []
    seen: set[str] = set()
    with open(path, "r", encoding="utf-8") as f:
        for lineno, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                raise ValueError(f"{path}:{lineno}: no '=' in vector line {line!r}")
            name, _, hexstr = line.partition("=")
            name = name.strip()
            hexstr = "".join(hexstr.split())
            if not _NAME_RE.match(name):
                raise ValueError(f"{path}:{lineno}: bad vector name {name!r}")
            if name in seen:
                raise ValueError(f"{path}:{lineno}: duplicate vector name {name!r}")
            if len(hexstr) % 2 != 0 or not re.fullmatch(r"[0-9A-Fa-f]*", hexstr):
                raise ValueError(f"{path}:{lineno}: {name!r} is not an even-length hex string")
            seen.add(name)
            vectors.append((name, bytes.fromhex(hexstr)))
    return vectors


def render(vectors: list[tuple[str, bytes]]) -> str:
    lines = [
        "/* Auto-generated by tests/gen_protocol_vectors_header.py from",
        " * tests/protocol_vectors.txt -- DO NOT EDIT, DO NOT COMMIT.",
        " * Regenerated on every build (tests/unit/CMakeLists.txt). */",
        "#ifndef GD32_BRIDGE_PROTOCOL_VECTORS_GEN_H",
        "#define GD32_BRIDGE_PROTOCOL_VECTORS_GEN_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "\tconst char    *name;",
        "\tconst uint8_t *bytes;",
        "\tsize_t         len;",
        "} pv_vector_t;",
        "",
    ]
    for i, (_name, data) in enumerate(vectors):
        byte_list = ", ".join(f"0x{b:02X}u" for b in data)
        lines.append(f"static const uint8_t pv_bytes_{i}[] = {{ {byte_list} }};")
    lines.append("")
    lines.append("static const pv_vector_t pv_vectors[] = {")
    for i, (name, data) in enumerate(vectors):
        lines.append(f'\t{{ "{name}", pv_bytes_{i}, {len(data)}u }},')
    lines.append("};")
    lines.append("")
    lines.append(f"#define PV_VECTOR_COUNT {len(vectors)}u")
    lines.append("")
    lines.append("#endif /* GD32_BRIDGE_PROTOCOL_VECTORS_GEN_H */")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} <vectors.txt> <out.h>", file=sys.stderr)
        return 2
    vectors = parse_vectors(argv[1])
    if not vectors:
        print(f"{argv[1]}: no vectors parsed -- refusing to emit an empty header", file=sys.stderr)
        return 1
    text = render(vectors)
    out_path = argv[2]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    tmp_path = out_path + ".tmp"
    with open(tmp_path, "w", encoding="ascii") as f:
        f.write(text)
    os.replace(tmp_path, out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
