# SPDX-License-Identifier: Apache-2.0
#
# Build-time build-id baker (cmake -P script).  Composes
#
#     GD32_BRIDGE_BUILD_ID = "<fw-version>+<git-sha-prefix>"
#
# at EXACTLY 20 ASCII characters (protocol.c _Static_asserts the
# length: the GET_BUILD_ID reply is a fixed 20-byte frame) and writes
# it into a generated header, ONLY-IF-CHANGED so incremental builds
# don't recompile protocol.c needlessly.
#
# This runs on EVERY build (driven by an always-out-of-date custom
# target), which is the whole point: the configure-time approach baked
# a stale id whenever HEAD or firmware-version.txt moved without a
# reconfigure -- that exact staleness failed an OTA upgrade check on
# the bench (2026-06-04).  Build-time regeneration kills both axes.
#
# Expected -D arguments:
#   VERSION_FILE  -- path to firmware-version.txt
#   SOURCE_DIR    -- a directory inside the git checkout (for git -C)
#   OUT_HEADER    -- path of the header to (re)generate
#
# No-git builds (release tarball, CI cache miss) degrade to an all-zero
# sha field -- the same wire value the pre-hook firmware always sent.

if(NOT DEFINED VERSION_FILE OR NOT DEFINED SOURCE_DIR OR NOT DEFINED OUT_HEADER)
    message(FATAL_ERROR "gen_build_id.cmake needs -DVERSION_FILE= -DSOURCE_DIR= -DOUT_HEADER=")
endif()

file(STRINGS ${VERSION_FILE} GD32_BRIDGE_FW_VERSION LIMIT_COUNT 1)
string(LENGTH "${GD32_BRIDGE_FW_VERSION}" _ver_len)
# 20-char frame = <ver> + '+' + <sha-field>; field width adapts to the
# version length (e.g. "0.2.8" -> 14 hex chars of sha).
math(EXPR _sha_field_len "19 - ${_ver_len}")
if(_sha_field_len LESS 1)
    message(FATAL_ERROR "firmware-version.txt too long for the 20-char build-id frame")
endif()

execute_process(
    COMMAND git -C ${SOURCE_DIR} rev-parse HEAD
    OUTPUT_VARIABLE _sha
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _git_rc
    ERROR_QUIET)
if(NOT _git_rc EQUAL 0)
    string(REPEAT "0" 40 _sha) # not a git checkout: zero sha, as before the hook
endif()
string(SUBSTRING "${_sha}" 0 ${_sha_field_len} _sha_field)

set(_id "${GD32_BRIDGE_FW_VERSION}+${_sha_field}")
string(LENGTH "${_id}" _id_len)
if(NOT _id_len EQUAL 20)
    message(FATAL_ERROR "composed build-id '${_id}' is ${_id_len} chars, want 20")
endif()

set(_tmp ${OUT_HEADER}.tmp)
file(WRITE ${_tmp} "/* Auto-generated by cmake/gen_build_id.cmake -- do not edit, do not
 * commit.  Regenerated on every build; copy_if_different keeps the
 * timestamp stable when HEAD and firmware-version.txt are unchanged. */
#ifndef GD32_BRIDGE_BUILD_ID
#define GD32_BRIDGE_BUILD_ID \"${_id}\"
#endif
")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${_tmp} ${OUT_HEADER})
file(REMOVE ${_tmp})
