/* Auto-generated by tests/gen_protocol_vectors_header.py from
 * tests/protocol_vectors.txt -- DO NOT EDIT, DO NOT COMMIT.
 * Regenerated on every build (tests/unit/CMakeLists.txt). */
#ifndef GD32_BRIDGE_PROTOCOL_VECTORS_GEN_H
#define GD32_BRIDGE_PROTOCOL_VECTORS_GEN_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
	const char    *name;
	const uint8_t *bytes;
	size_t         len;
} pv_vector_t;

static const uint8_t pv_bytes_0[] = { 0x31u, 0x32u, 0x33u, 0x34u, 0x35u, 0x36u, 0x37u, 0x38u, 0x39u };
static const uint8_t pv_bytes_1[] = { 0x29u, 0xB1u };
static const uint8_t pv_bytes_2[] = { 0x31u, 0x32u, 0x33u, 0x34u, 0x35u, 0x36u, 0x37u, 0x38u, 0x39u, 0x30u };
static const uint8_t pv_bytes_3[] = { 0xA5u, 0x00u, 0x84u, 0xFFu };
static const uint8_t pv_bytes_4[] = { 0xA5u, 0x00u, 0x84u, 0xFFu };
static const uint8_t pv_bytes_5[] = { 0xA5u, 0x01u, 0xA5u, 0xEFu };
static const uint8_t pv_bytes_6[] = { 0xA5u, 0x00u, 0x00u, 0x0Eu, 0x00u, 0x30u, 0x3Bu };
static const uint8_t pv_bytes_7[] = { 0x00u, 0x00u, 0xF0u, 0xE1u };
static const uint8_t pv_bytes_8[] = { 0x00u, 0xF0u, 0xE1u };
static const uint8_t pv_bytes_9[] = { 0xA5u, 0x50u, 0x00u, 0x00u, 0x72u, 0x06u, 0xF6u, 0xB7u };
static const uint8_t pv_bytes_10[] = { 0xA5u, 0x51u, 0x01u, 0x5Fu, 0xB7u };
static const uint8_t pv_bytes_11[] = { 0xA5u, 0x60u, 0x00u, 0xDAu, 0x91u };
static const uint8_t pv_bytes_12[] = { 0xA5u, 0x61u, 0x03u, 0x88u, 0x92u };
static const uint8_t pv_bytes_13[] = { 0xA5u, 0x70u, 0x00u, 0xA9u, 0x92u };
static const uint8_t pv_bytes_14[] = { 0xA5u, 0x41u, 0x01u, 0x2Cu, 0xB4u };
static const uint8_t pv_bytes_15[] = { 0xA5u, 0x41u, 0x00u, 0x0Du, 0xA4u };
static const uint8_t pv_bytes_16[] = { 0xA5u, 0x06u, 0x42u, 0x9Fu };
static const uint8_t pv_bytes_17[] = { 0xA5u, 0x22u, 0x00u, 0x01u, 0xD0u, 0x07u, 0x00u, 0x00u, 0x01u, 0x70u, 0xB0u };
static const uint8_t pv_bytes_18[] = { 0xA5u, 0x32u, 0x03u, 0x00u, 0x10u, 0x00u, 0x5Fu, 0x00u, 0x10u, 0x9Cu, 0x02u };
static const uint8_t pv_bytes_19[] = { 0xA5u, 0x33u, 0x00u, 0x00u, 0x00u, 0xE8u, 0x03u, 0x00u, 0x00u, 0x20u, 0xA1u };
static const uint8_t pv_bytes_20[] = { 0xA5u, 0x34u, 0x00u, 0x20u, 0xF4u, 0xEFu };
static const uint8_t pv_bytes_21[] = { 0xA5u, 0x35u, 0x00u, 0x90u, 0x60u };
static const uint8_t pv_bytes_22[] = { 0xA5u, 0x80u, 0x10u, 0x59u, 0x93u };
static const uint8_t pv_bytes_23[] = { 0xA5u, 0x90u, 0x05u, 0x01u, 0x00u, 0x00u, 0x00u, 0x00u, 0x80u, 0x40u, 0x00u, 0x00u, 0x00u, 0x00u, 0xABu, 0x55u };
static const uint8_t pv_bytes_24[] = { 0xA5u, 0x36u, 0x11u, 0xA9u };
static const uint8_t pv_bytes_25[] = { 0xA5u, 0x23u, 0x00u, 0x02u, 0x27u, 0x2Du };
static const uint8_t pv_bytes_26[] = { 0xA5u, 0x26u, 0x00u, 0x00u, 0x00u, 0x00u, 0xE8u, 0x03u, 0x00u, 0x00u, 0x7Du, 0x5Bu };
static const uint8_t pv_bytes_27[] = { 0xA5u, 0x28u, 0x02u, 0x00u, 0x03u, 0x00u, 0x00u, 0x00u, 0x10u, 0x27u, 0x00u, 0x00u, 0xA3u, 0x48u };
static const uint8_t pv_bytes_28[] = { 0xA5u, 0x37u, 0x30u, 0xB9u };
static const uint8_t pv_bytes_29[] = { 0xA5u, 0x38u, 0x00u, 0x00u, 0x02u, 0x00u, 0x00u, 0x04u, 0x00u, 0x01u, 0x00u, 0x00u, 0x00u, 0x20u, 0x04u };
static const uint8_t pv_bytes_30[] = { 0xA5u, 0x39u, 0x00u, 0x00u, 0xC7u, 0x89u };
static const uint8_t pv_bytes_31[] = { 0xA5u, 0xF0u, 0xF8u, 0xA3u, 0x00u, 0x00u, 0xEFu, 0xBEu, 0xADu, 0xDEu, 0xA8u, 0x50u };
static const uint8_t pv_bytes_32[] = { 0xA5u, 0xF0u, 0xF8u, 0xA3u, 0x00u, 0x00u, 0xEFu, 0xBEu, 0xADu, 0xDEu, 0x00u, 0x02u, 0x09u, 0x52u, 0x3Du };
static const uint8_t pv_bytes_33[] = { 0xA5u, 0x00u, 0x3Cu, 0x00u, 0x01u, 0xDAu, 0xB8u };
static const uint8_t pv_bytes_34[] = { 0xA5u, 0xF1u, 0x00u, 0x00u, 0x00u, 0x00u, 0x08u, 0x01u, 0x02u, 0x03u, 0x04u, 0x05u, 0x06u, 0x07u, 0x08u, 0x40u, 0xB1u };
static const uint8_t pv_bytes_35[] = { 0xA5u, 0x00u, 0x08u, 0x00u, 0x00u, 0x00u, 0xFAu, 0x29u };
static const uint8_t pv_bytes_36[] = { 0xA5u, 0xF2u, 0xD9u, 0x30u };
static const uint8_t pv_bytes_37[] = { 0xA5u, 0x00u, 0xEFu, 0xBEu, 0xADu, 0xDEu, 0x01u, 0xDCu, 0x99u };
static const uint8_t pv_bytes_38[] = { 0xA5u, 0xF3u, 0xF8u, 0x20u };
static const uint8_t pv_bytes_39[] = { 0xA5u, 0xF4u, 0x1Fu, 0x50u };
static const uint8_t pv_bytes_40[] = { 0xA5u, 0xF5u, 0x3Eu, 0x40u };
static const uint8_t pv_bytes_41[] = { 0xA5u, 0x00u, 0x01u, 0x00u, 0x01u, 0x01u, 0x00u, 0x00u, 0x4Du, 0xFBu };
static const uint8_t pv_bytes_42[] = { 0xA5u, 0x00u, 0x04u, 0x00u, 0xFFu, 0x01u, 0x00u, 0x05u, 0xFEu, 0xD5u };
static const uint8_t pv_bytes_43[] = { 0xA5u, 0xF6u, 0x5Du, 0x70u };
static const uint8_t pv_bytes_44[] = { 0xA5u, 0x02u, 0xC6u, 0xDFu };
static const uint8_t pv_bytes_45[] = { 0xA5u, 0x81u, 0x01u, 0x78u, 0xA2u };
static const uint8_t pv_bytes_46[] = { 0xA5u, 0x10u, 0x01u, 0xA2u, 0x89u };
static const uint8_t pv_bytes_47[] = { 0xA5u, 0x50u, 0x71u, 0xA5u };
static const uint8_t pv_bytes_48[] = { 0xA5u, 0x02u, 0xC6u, 0xDFu };
static const uint8_t pv_bytes_49[] = { 0xA5u, 0x03u, 0xE7u, 0xCFu };
static const uint8_t pv_bytes_50[] = { 0xA5u, 0x00u, 0x00u, 0xF0u, 0x9Au };
static const uint8_t pv_bytes_51[] = { 0xA5u, 0x10u, 0x01u, 0x00u, 0x00u, 0x00u, 0xD7u, 0xDEu };
static const uint8_t pv_bytes_52[] = { 0xA5u, 0x11u, 0x01u, 0x00u, 0x00u, 0x00u, 0x01u, 0x00u, 0x00u, 0x00u, 0xCAu, 0x77u };
static const uint8_t pv_bytes_53[] = { 0xA5u, 0x20u, 0x00u, 0x00u, 0x40u, 0x42u, 0x0Fu, 0x00u, 0x20u, 0xA1u, 0x07u, 0x00u, 0x8Au, 0x4Eu };
static const uint8_t pv_bytes_54[] = { 0xA5u, 0x21u, 0x00u, 0x27u, 0xAFu };
static const uint8_t pv_bytes_55[] = { 0xA5u, 0x30u, 0x00u, 0x04u, 0xD2u, 0x57u };
static const uint8_t pv_bytes_56[] = { 0xA5u, 0x40u, 0x40u, 0xB7u };
static const uint8_t pv_bytes_57[] = { 0xA5u, 0x00u, 0xFFu, 0x00u, 0x84u };
static const uint8_t pv_bytes_58[] = { 0xA5u, 0x05u, 0x21u, 0xAFu };
static const uint8_t pv_bytes_59[] = { 0xA5u, 0x24u, 0x00u, 0xD2u, 0x50u };
static const uint8_t pv_bytes_60[] = { 0xA5u, 0x25u, 0x00u, 0xE3u, 0x63u };
static const uint8_t pv_bytes_61[] = { 0xA5u, 0x27u, 0x00u, 0x01u, 0x00u, 0x6Du, 0x4Du };
static const uint8_t pv_bytes_62[] = { 0xA5u, 0x3Au, 0x00u, 0x00u, 0x00u, 0x04u, 0xFDu, 0xA6u };
static const uint8_t pv_bytes_63[] = { 0xA5u, 0x00u, 0x01u, 0x00u, 0x00u, 0x00u, 0x0Au, 0x00u, 0x02u, 0x00u, 0x00u, 0x80u, 0x40u, 0x00u, 0x00u, 0x00u, 0x41u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x96u, 0xEDu };

static const pv_vector_t pv_vectors[] = {
	{ "crc16_ccitt_false_ref_string", pv_bytes_0, 9u },
	{ "crc16_ccitt_false_ref_result", pv_bytes_1, 2u },
	{ "crc16_ccitt_false_test_string", pv_bytes_2, 10u },
	{ "spi_ping_request", pv_bytes_3, 4u },
	{ "spi_ping_reply_ok", pv_bytes_4, 4u },
	{ "spi_get_version_request", pv_bytes_5, 4u },
	{ "spi_get_version_reply_v0_14_0", pv_bytes_6, 7u },
	{ "i2c_ping_write", pv_bytes_7, 4u },
	{ "i2c_ping_read_ok", pv_bytes_8, 3u },
	{ "spi_dac_set_ch0_1650mv_request", pv_bytes_9, 8u },
	{ "spi_dac_get_ch1_request", pv_bytes_10, 5u },
	{ "spi_qenc_read_ch0_request", pv_bytes_11, 5u },
	{ "spi_qenc_reset_ch3_request", pv_bytes_12, 5u },
	{ "spi_counter_read_ch0_request", pv_bytes_13, 5u },
	{ "spi_se_reset_assert_request", pv_bytes_14, 5u },
	{ "spi_se_reset_release_request", pv_bytes_15, 5u },
	{ "spi_reply_nosupport", pv_bytes_16, 4u },
	{ "spi_pwm_configure_ch0_request", pv_bytes_17, 11u },
	{ "spi_adc_configure_ch3_request", pv_bytes_18, 11u },
	{ "spi_adc_stream_begin_stream0_ch0_1ksps_request", pv_bytes_19, 11u },
	{ "spi_adc_stream_read_stream0_max32_request", pv_bytes_20, 6u },
	{ "spi_adc_stream_end_stream0_request", pv_bytes_21, 5u },
	{ "spi_trng_read_16_request", pv_bytes_22, 5u },
	{ "spi_tmu_compute_sqrt_f32_4p0_request", pv_bytes_23, 16u },
	{ "spi_adc_stream_configure_dsp_probe_request", pv_bytes_24, 4u },
	{ "spi_pwm_capture_begin_probe_request", pv_bytes_25, 6u },
	{ "spi_pwm_single_pulse_probe_request", pv_bytes_26, 12u },
	{ "spi_power_mode_set_probe_request", pv_bytes_27, 14u },
	{ "spi_adc_dsp_chain_open_probe_request", pv_bytes_28, 4u },
	{ "spi_adc_dsp_stage_push_window_hann_request", pv_bytes_29, 15u },
	{ "spi_adc_dsp_chain_bind_probe_request", pv_bytes_30, 6u },
	{ "spi_ota_begin_request", pv_bytes_31, 12u },
	{ "spi_ota_begin_request_v0_7", pv_bytes_32, 15u },
	{ "spi_ota_begin_reply_slot_b", pv_bytes_33, 7u },
	{ "spi_ota_write_chunk_off0_8b_request", pv_bytes_34, 17u },
	{ "spi_ota_write_chunk_reply_8b", pv_bytes_35, 8u },
	{ "spi_ota_verify_request", pv_bytes_36, 4u },
	{ "spi_ota_verify_reply_match", pv_bytes_37, 9u },
	{ "spi_ota_commit_request", pv_bytes_38, 4u },
	{ "spi_ota_rollback_request", pv_bytes_39, 4u },
	{ "spi_ota_get_state_request", pv_bytes_40, 4u },
	{ "spi_ota_get_state_reply_ready", pv_bytes_41, 10u },
	{ "spi_ota_get_state_reply_error_verify_crc", pv_bytes_42, 10u },
	{ "spi_ota_abort_request", pv_bytes_43, 4u },
	{ "spi_ota_reply_not_ready", pv_bytes_44, 4u },
	{ "spi_link_features_request", pv_bytes_45, 5u },
	{ "spi_link_features_reply_granted_seq1", pv_bytes_46, 5u },
	{ "spi_ping_reply_ok_seq5", pv_bytes_47, 4u },
	{ "spi_get_build_id_request", pv_bytes_48, 4u },
	{ "spi_reset_reason_request", pv_bytes_49, 4u },
	{ "spi_reset_reason_reply_unknown", pv_bytes_50, 5u },
	{ "spi_gpio_read_mask_bit0_request", pv_bytes_51, 8u },
	{ "spi_gpio_write_mask_bit0_high_request", pv_bytes_52, 12u },
	{ "spi_pwm_set_ch0_1ms_period_500us_duty_request", pv_bytes_53, 14u },
	{ "spi_pwm_get_ch0_request", pv_bytes_54, 5u },
	{ "spi_adc_read_ch0_4samples_request", pv_bytes_55, 6u },
	{ "spi_da9292_status_forward_request", pv_bytes_56, 4u },
	{ "spi_da9292_status_forward_reply_no_sample", pv_bytes_57, 5u },
	{ "spi_reply_io", pv_bytes_58, 4u },
	{ "spi_pwm_capture_read_ch0_request", pv_bytes_59, 5u },
	{ "spi_pwm_capture_end_ch0_request", pv_bytes_60, 5u },
	{ "spi_timer_sync_t0_master_t7_slave_request", pv_bytes_61, 7u },
	{ "spi_adc_spectrum_read_stream0_request", pv_bytes_62, 8u },
	{ "spi_adc_spectrum_read_reply_example", pv_bytes_63, 27u },
};

#define PV_VECTOR_COUNT 64u

#endif /* GD32_BRIDGE_PROTOCOL_VECTORS_GEN_H */
