# CMake generated Testfile for 
# Source directory: /home/caner/gd32-int/upd/tests/unit
# Build directory: /home/caner/gd32-int/upd/bt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ota_slot_a]=] "/home/caner/gd32-int/upd/bt/test_ota_slot_a")
set_tests_properties([=[ota_slot_a]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;119;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[ota_slot_b]=] "/home/caner/gd32-int/upd/bt/test_ota_slot_b")
set_tests_properties([=[ota_slot_b]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;119;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[crc32]=] "/home/caner/gd32-int/upd/bt/test_crc32")
set_tests_properties([=[crc32]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;130;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[crc16]=] "/home/caner/gd32-int/upd/bt/test_crc16")
set_tests_properties([=[crc16]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;144;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[transport_spi]=] "/home/caner/gd32-int/upd/bt/test_transport_spi")
set_tests_properties([=[transport_spi]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;159;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[fault_diag]=] "/home/caner/gd32-int/upd/bt/test_fault_diag")
set_tests_properties([=[fault_diag]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;173;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[i2c_event_priority]=] "/home/caner/gd32-int/upd/bt/test_i2c_event_priority")
set_tests_properties([=[i2c_event_priority]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;187;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[timer_sync_iti]=] "/home/caner/gd32-int/upd/bt/test_timer_sync_iti")
set_tests_properties([=[timer_sync_iti]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;201;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[power_wake]=] "/home/caner/gd32-int/upd/bt/test_power_wake")
set_tests_properties([=[power_wake]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;222;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[timer_sync]=] "/home/caner/gd32-int/upd/bt/test_timer_sync")
set_tests_properties([=[timer_sync]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;246;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[pwm_preload_transaction]=] "/home/caner/gd32-int/upd/bt/test_pwm_preload_transaction")
set_tests_properties([=[pwm_preload_transaction]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;264;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[i2c_timeout]=] "/home/caner/gd32-int/upd/bt/test_i2c_timeout")
set_tests_properties([=[i2c_timeout]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;279;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[i2c_recovery]=] "/home/caner/gd32-int/upd/bt/test_i2c_recovery")
set_tests_properties([=[i2c_recovery]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;293;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[gpio_grouped]=] "/home/caner/gd32-int/upd/bt/test_gpio_grouped")
set_tests_properties([=[gpio_grouped]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;311;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[tmu_q31_scale]=] "/home/caner/gd32-int/upd/bt/test_tmu_q31_scale")
set_tests_properties([=[tmu_q31_scale]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;326;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[pwm_ownership]=] "/home/caner/gd32-int/upd/bt/test_pwm_ownership")
set_tests_properties([=[pwm_ownership]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;333;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[pwm_gd32]=] "/home/caner/gd32-int/upd/bt/test_pwm_gd32")
set_tests_properties([=[pwm_gd32]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;347;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[adc_seq]=] "/home/caner/gd32-int/upd/bt/test_adc_seq")
set_tests_properties([=[adc_seq]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;382;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[fmc_ota_guard]=] "/home/caner/gd32-int/upd/bt/test_fmc_ota_guard")
set_tests_properties([=[fmc_ota_guard]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;392;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[transport_i2c]=] "/home/caner/gd32-int/upd/bt/test_transport_i2c")
set_tests_properties([=[transport_i2c]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;411;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[protocol]=] "/home/caner/gd32-int/upd/bt/test_protocol")
set_tests_properties([=[protocol]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;435;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[adc_dsp]=] "/home/caner/gd32-int/upd/bt/test_adc_dsp")
set_tests_properties([=[adc_dsp]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;454;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
add_test([=[protocol_vectors]=] "/home/caner/gd32-int/upd/bt/test_protocol_vectors")
set_tests_properties([=[protocol_vectors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;497;add_test;/home/caner/gd32-int/upd/tests/unit/CMakeLists.txt;0;")
